// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Jub_Filecoin.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CommonProtosBip44Path;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FilecoinProtosJubFilecoinRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FilecoinProtosJubFilecoinRoot : GPBRootObject
@end

#pragma mark - FilecoinProtosContextCfgFIL

typedef GPB_ENUM(FilecoinProtosContextCfgFIL_FieldNumber) {
  FilecoinProtosContextCfgFIL_FieldNumber_MainPath = 1,
};

@interface FilecoinProtosContextCfgFIL : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mainPath;

@end

#pragma mark - FilecoinProtosTransactionFIL

typedef GPB_ENUM(FilecoinProtosTransactionFIL_FieldNumber) {
  FilecoinProtosTransactionFIL_FieldNumber_Path = 1,
  FilecoinProtosTransactionFIL_FieldNumber_Nonce = 2,
  FilecoinProtosTransactionFIL_FieldNumber_GasLimit = 3,
  FilecoinProtosTransactionFIL_FieldNumber_GasFeeCapInAtto = 4,
  FilecoinProtosTransactionFIL_FieldNumber_GasPremiumInAtto = 5,
  FilecoinProtosTransactionFIL_FieldNumber_To = 6,
  FilecoinProtosTransactionFIL_FieldNumber_ValueInAtto = 7,
  FilecoinProtosTransactionFIL_FieldNumber_Input = 8,
};

@interface FilecoinProtosTransactionFIL : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) CommonProtosBip44Path *path;
/** Test to see if @c path has been set. */
@property(nonatomic, readwrite) BOOL hasPath;

@property(nonatomic, readwrite) uint32_t nonce;

@property(nonatomic, readwrite) uint32_t gasLimit;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gasFeeCapInAtto;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gasPremiumInAtto;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *valueInAtto;

@property(nonatomic, readwrite, copy, null_resettable) NSString *input;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
