// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jubiterblue.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class JuBiterProtosAdvertisementData;
@class JuBiterProtosBluetoothDevice;
@class JuBiterProtosInt32Value;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum JuBiterProtosBluetoothState_State

typedef GPB_ENUM(JuBiterProtosBluetoothState_State) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  JuBiterProtosBluetoothState_State_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  JuBiterProtosBluetoothState_State_Unknown = 0,
  JuBiterProtosBluetoothState_State_Unavailable = 1,
  JuBiterProtosBluetoothState_State_Unauthorized = 2,
  JuBiterProtosBluetoothState_State_TurningOn = 3,
  JuBiterProtosBluetoothState_State_On = 4,
  JuBiterProtosBluetoothState_State_TurningOff = 5,
  JuBiterProtosBluetoothState_State_Off = 6,
};

GPBEnumDescriptor *JuBiterProtosBluetoothState_State_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL JuBiterProtosBluetoothState_State_IsValidValue(int32_t value);

#pragma mark - Enum JuBiterProtosBluetoothDevice_Type

typedef GPB_ENUM(JuBiterProtosBluetoothDevice_Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  JuBiterProtosBluetoothDevice_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  JuBiterProtosBluetoothDevice_Type_Unknown = 0,
  JuBiterProtosBluetoothDevice_Type_Classic = 1,
  JuBiterProtosBluetoothDevice_Type_Le = 2,
  JuBiterProtosBluetoothDevice_Type_Dual = 3,
};

GPBEnumDescriptor *JuBiterProtosBluetoothDevice_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL JuBiterProtosBluetoothDevice_Type_IsValidValue(int32_t value);

#pragma mark - Enum JuBiterProtosDeviceStateResponse_BluetoothDeviceState

typedef GPB_ENUM(JuBiterProtosDeviceStateResponse_BluetoothDeviceState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  JuBiterProtosDeviceStateResponse_BluetoothDeviceState_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  JuBiterProtosDeviceStateResponse_BluetoothDeviceState_Disconnected = 0,
  JuBiterProtosDeviceStateResponse_BluetoothDeviceState_Connecting = 1,
  JuBiterProtosDeviceStateResponse_BluetoothDeviceState_Connected = 2,
  JuBiterProtosDeviceStateResponse_BluetoothDeviceState_Disconnecting = 3,
};

GPBEnumDescriptor *JuBiterProtosDeviceStateResponse_BluetoothDeviceState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL JuBiterProtosDeviceStateResponse_BluetoothDeviceState_IsValidValue(int32_t value);

#pragma mark - JuBiterProtosJubiterblueRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface JuBiterProtosJubiterblueRoot : GPBRootObject
@end

#pragma mark - JuBiterProtosInt32Value

typedef GPB_ENUM(JuBiterProtosInt32Value_FieldNumber) {
  JuBiterProtosInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int32`.
 *
 * Allows for nullability of fields in messages
 **/
@interface JuBiterProtosInt32Value : GPBMessage

/** The int32 value. */
@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - JuBiterProtosBluetoothState

typedef GPB_ENUM(JuBiterProtosBluetoothState_FieldNumber) {
  JuBiterProtosBluetoothState_FieldNumber_State = 1,
};

@interface JuBiterProtosBluetoothState : GPBMessage

@property(nonatomic, readwrite) JuBiterProtosBluetoothState_State state;

@end

/**
 * Fetches the raw value of a @c JuBiterProtosBluetoothState's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t JuBiterProtosBluetoothState_State_RawValue(JuBiterProtosBluetoothState *message);
/**
 * Sets the raw value of an @c JuBiterProtosBluetoothState's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetJuBiterProtosBluetoothState_State_RawValue(JuBiterProtosBluetoothState *message, int32_t value);

#pragma mark - JuBiterProtosAdvertisementData

typedef GPB_ENUM(JuBiterProtosAdvertisementData_FieldNumber) {
  JuBiterProtosAdvertisementData_FieldNumber_LocalName = 1,
  JuBiterProtosAdvertisementData_FieldNumber_TxPowerLevel = 2,
  JuBiterProtosAdvertisementData_FieldNumber_Connectable = 3,
  JuBiterProtosAdvertisementData_FieldNumber_ManufacturerData = 4,
  JuBiterProtosAdvertisementData_FieldNumber_ServiceData = 5,
  JuBiterProtosAdvertisementData_FieldNumber_ServiceUuidsArray = 6,
};

@interface JuBiterProtosAdvertisementData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *localName;

@property(nonatomic, readwrite, strong, null_resettable) JuBiterProtosInt32Value *txPowerLevel;
/** Test to see if @c txPowerLevel has been set. */
@property(nonatomic, readwrite) BOOL hasTxPowerLevel;

@property(nonatomic, readwrite) BOOL connectable;

/** Map of manufacturers to their data */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32ObjectDictionary<NSData*> *manufacturerData;
/** The number of items in @c manufacturerData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger manufacturerData_Count;

/** Map of service UUIDs to their data. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSData*> *serviceData;
/** The number of items in @c serviceData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger serviceData_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *serviceUuidsArray;
/** The number of items in @c serviceUuidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger serviceUuidsArray_Count;

@end

#pragma mark - JuBiterProtosScanSettings

typedef GPB_ENUM(JuBiterProtosScanSettings_FieldNumber) {
  JuBiterProtosScanSettings_FieldNumber_AndroidScanMode = 1,
  JuBiterProtosScanSettings_FieldNumber_ServiceUuidsArray = 2,
};

@interface JuBiterProtosScanSettings : GPBMessage

@property(nonatomic, readwrite) int32_t androidScanMode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *serviceUuidsArray;
/** The number of items in @c serviceUuidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger serviceUuidsArray_Count;

@end

#pragma mark - JuBiterProtosScanResult

typedef GPB_ENUM(JuBiterProtosScanResult_FieldNumber) {
  JuBiterProtosScanResult_FieldNumber_Device = 1,
  JuBiterProtosScanResult_FieldNumber_AdvertisementData = 2,
  JuBiterProtosScanResult_FieldNumber_Rssi = 3,
};

@interface JuBiterProtosScanResult : GPBMessage

/** The received peer's ID. */
@property(nonatomic, readwrite, strong, null_resettable) JuBiterProtosBluetoothDevice *device;
/** Test to see if @c device has been set. */
@property(nonatomic, readwrite) BOOL hasDevice;

/** unused */
@property(nonatomic, readwrite, strong, null_resettable) JuBiterProtosAdvertisementData *advertisementData;
/** Test to see if @c advertisementData has been set. */
@property(nonatomic, readwrite) BOOL hasAdvertisementData;

/** unused */
@property(nonatomic, readwrite) int32_t rssi;

@end

#pragma mark - JuBiterProtosConnectRequest

typedef GPB_ENUM(JuBiterProtosConnectRequest_FieldNumber) {
  JuBiterProtosConnectRequest_FieldNumber_RemoteId = 1,
  JuBiterProtosConnectRequest_FieldNumber_Timeout = 2,
  JuBiterProtosConnectRequest_FieldNumber_AndroidAutoConnect = 3,
};

@interface JuBiterProtosConnectRequest : GPBMessage

/** mac or uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *remoteId;

@property(nonatomic, readwrite) int32_t timeout;

/** unused */
@property(nonatomic, readwrite) BOOL androidAutoConnect;

@end

#pragma mark - JuBiterProtosBluetoothDevice

typedef GPB_ENUM(JuBiterProtosBluetoothDevice_FieldNumber) {
  JuBiterProtosBluetoothDevice_FieldNumber_RemoteId = 1,
  JuBiterProtosBluetoothDevice_FieldNumber_Name = 2,
  JuBiterProtosBluetoothDevice_FieldNumber_Type = 3,
};

@interface JuBiterProtosBluetoothDevice : GPBMessage

/** mac or uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *remoteId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) JuBiterProtosBluetoothDevice_Type type;

@end

/**
 * Fetches the raw value of a @c JuBiterProtosBluetoothDevice's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t JuBiterProtosBluetoothDevice_Type_RawValue(JuBiterProtosBluetoothDevice *message);
/**
 * Sets the raw value of an @c JuBiterProtosBluetoothDevice's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetJuBiterProtosBluetoothDevice_Type_RawValue(JuBiterProtosBluetoothDevice *message, int32_t value);

#pragma mark - JuBiterProtosDeviceStateResponse

typedef GPB_ENUM(JuBiterProtosDeviceStateResponse_FieldNumber) {
  JuBiterProtosDeviceStateResponse_FieldNumber_RemoteId = 1,
  JuBiterProtosDeviceStateResponse_FieldNumber_State = 2,
  JuBiterProtosDeviceStateResponse_FieldNumber_DeviceId = 3,
};

@interface JuBiterProtosDeviceStateResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *remoteId;

@property(nonatomic, readwrite) JuBiterProtosDeviceStateResponse_BluetoothDeviceState state;

@property(nonatomic, readwrite) int32_t deviceId;

@end

/**
 * Fetches the raw value of a @c JuBiterProtosDeviceStateResponse's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t JuBiterProtosDeviceStateResponse_State_RawValue(JuBiterProtosDeviceStateResponse *message);
/**
 * Sets the raw value of an @c JuBiterProtosDeviceStateResponse's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetJuBiterProtosDeviceStateResponse_State_RawValue(JuBiterProtosDeviceStateResponse *message, int32_t value);

#pragma mark - JuBiterProtosConnectedDevicesResponse

typedef GPB_ENUM(JuBiterProtosConnectedDevicesResponse_FieldNumber) {
  JuBiterProtosConnectedDevicesResponse_FieldNumber_DevicesArray = 1,
};

@interface JuBiterProtosConnectedDevicesResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<JuBiterProtosBluetoothDevice*> *devicesArray;
/** The number of items in @c devicesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger devicesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
