// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Jub_Ethereum.proto

package com.jubiter.sdk.proto;

public final class EthereumProtos {
  private EthereumProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContextCfgETHOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Ethereum.ContextCfgETH)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string main_path = 1;</code>
     */
    java.lang.String getMainPath();
    /**
     * <code>string main_path = 1;</code>
     */
    com.google.protobuf.ByteString
        getMainPathBytes();

    /**
     * <code>uint32 chain_id = 2;</code>
     */
    int getChainId();
  }
  /**
   * Protobuf type {@code JUB.Proto.Ethereum.ContextCfgETH}
   */
  public  static final class ContextCfgETH extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Ethereum.ContextCfgETH)
      ContextCfgETHOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContextCfgETH.newBuilder() to construct.
    private ContextCfgETH(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContextCfgETH() {
      mainPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContextCfgETH();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContextCfgETH(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mainPath_ = s;
              break;
            }
            case 16: {

              chainId_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_ContextCfgETH_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.class, com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.Builder.class);
    }

    public static final int MAIN_PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object mainPath_;
    /**
     * <code>string main_path = 1;</code>
     */
    public java.lang.String getMainPath() {
      java.lang.Object ref = mainPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainPath_ = s;
        return s;
      }
    }
    /**
     * <code>string main_path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMainPathBytes() {
      java.lang.Object ref = mainPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 2;
    private int chainId_;
    /**
     * <code>uint32 chain_id = 2;</code>
     */
    public int getChainId() {
      return chainId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMainPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mainPath_);
      }
      if (chainId_ != 0) {
        output.writeUInt32(2, chainId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMainPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mainPath_);
      }
      if (chainId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, chainId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH)) {
        return super.equals(obj);
      }
      com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH other = (com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH) obj;

      if (!getMainPath()
          .equals(other.getMainPath())) return false;
      if (getChainId()
          != other.getChainId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAIN_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getMainPath().hashCode();
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Ethereum.ContextCfgETH}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Ethereum.ContextCfgETH)
        com.jubiter.sdk.proto.EthereumProtos.ContextCfgETHOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_ContextCfgETH_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.class, com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mainPath_ = "";

        chainId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor;
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH getDefaultInstanceForType() {
        return com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.getDefaultInstance();
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH build() {
        com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH buildPartial() {
        com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH result = new com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH(this);
        result.mainPath_ = mainPath_;
        result.chainId_ = chainId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH) {
          return mergeFrom((com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH other) {
        if (other == com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH.getDefaultInstance()) return this;
        if (!other.getMainPath().isEmpty()) {
          mainPath_ = other.mainPath_;
          onChanged();
        }
        if (other.getChainId() != 0) {
          setChainId(other.getChainId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mainPath_ = "";
      /**
       * <code>string main_path = 1;</code>
       */
      public java.lang.String getMainPath() {
        java.lang.Object ref = mainPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mainPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMainPathBytes() {
        java.lang.Object ref = mainPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder setMainPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder clearMainPath() {
        
        mainPath_ = getDefaultInstance().getMainPath();
        onChanged();
        return this;
      }
      /**
       * <code>string main_path = 1;</code>
       */
      public Builder setMainPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainPath_ = value;
        onChanged();
        return this;
      }

      private int chainId_ ;
      /**
       * <code>uint32 chain_id = 2;</code>
       */
      public int getChainId() {
        return chainId_;
      }
      /**
       * <code>uint32 chain_id = 2;</code>
       */
      public Builder setChainId(int value) {
        
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chain_id = 2;</code>
       */
      public Builder clearChainId() {
        
        chainId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Ethereum.ContextCfgETH)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Ethereum.ContextCfgETH)
    private static final com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH();
    }

    public static com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContextCfgETH>
        PARSER = new com.google.protobuf.AbstractParser<ContextCfgETH>() {
      @java.lang.Override
      public ContextCfgETH parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContextCfgETH(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContextCfgETH> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContextCfgETH> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jubiter.sdk.proto.EthereumProtos.ContextCfgETH getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionETHOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JUB.Proto.Ethereum.TransactionETH)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    boolean hasPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    com.jubiter.sdk.proto.CommonProtos.Bip44Path getPath();
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder getPathOrBuilder();

    /**
     * <code>uint32 nonce = 2;</code>
     */
    int getNonce();

    /**
     * <code>uint32 gas_limit = 3;</code>
     */
    int getGasLimit();

    /**
     * <code>string gas_price_in_wei = 4;</code>
     */
    java.lang.String getGasPriceInWei();
    /**
     * <code>string gas_price_in_wei = 4;</code>
     */
    com.google.protobuf.ByteString
        getGasPriceInWeiBytes();

    /**
     * <code>string to = 5;</code>
     */
    java.lang.String getTo();
    /**
     * <code>string to = 5;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string value_in_wei = 6;</code>
     */
    java.lang.String getValueInWei();
    /**
     * <code>string value_in_wei = 6;</code>
     */
    com.google.protobuf.ByteString
        getValueInWeiBytes();

    /**
     * <code>string input = 7;</code>
     */
    java.lang.String getInput();
    /**
     * <code>string input = 7;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();
  }
  /**
   * Protobuf type {@code JUB.Proto.Ethereum.TransactionETH}
   */
  public  static final class TransactionETH extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JUB.Proto.Ethereum.TransactionETH)
      TransactionETHOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionETH.newBuilder() to construct.
    private TransactionETH(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionETH() {
      gasPriceInWei_ = "";
      to_ = "";
      valueInWei_ = "";
      input_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionETH();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionETH(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder subBuilder = null;
              if (path_ != null) {
                subBuilder = path_.toBuilder();
              }
              path_ = input.readMessage(com.jubiter.sdk.proto.CommonProtos.Bip44Path.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(path_);
                path_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              nonce_ = input.readUInt32();
              break;
            }
            case 24: {

              gasLimit_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              gasPriceInWei_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              valueInWei_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              input_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_TransactionETH_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jubiter.sdk.proto.EthereumProtos.TransactionETH.class, com.jubiter.sdk.proto.EthereumProtos.TransactionETH.Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    private com.jubiter.sdk.proto.CommonProtos.Bip44Path path_;
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public boolean hasPath() {
      return path_ != null;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public com.jubiter.sdk.proto.CommonProtos.Bip44Path getPath() {
      return path_ == null ? com.jubiter.sdk.proto.CommonProtos.Bip44Path.getDefaultInstance() : path_;
    }
    /**
     * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
     */
    public com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
      return getPath();
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private int nonce_;
    /**
     * <code>uint32 nonce = 2;</code>
     */
    public int getNonce() {
      return nonce_;
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 3;
    private int gasLimit_;
    /**
     * <code>uint32 gas_limit = 3;</code>
     */
    public int getGasLimit() {
      return gasLimit_;
    }

    public static final int GAS_PRICE_IN_WEI_FIELD_NUMBER = 4;
    private volatile java.lang.Object gasPriceInWei_;
    /**
     * <code>string gas_price_in_wei = 4;</code>
     */
    public java.lang.String getGasPriceInWei() {
      java.lang.Object ref = gasPriceInWei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gasPriceInWei_ = s;
        return s;
      }
    }
    /**
     * <code>string gas_price_in_wei = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGasPriceInWeiBytes() {
      java.lang.Object ref = gasPriceInWei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gasPriceInWei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 5;
    private volatile java.lang.Object to_;
    /**
     * <code>string to = 5;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_IN_WEI_FIELD_NUMBER = 6;
    private volatile java.lang.Object valueInWei_;
    /**
     * <code>string value_in_wei = 6;</code>
     */
    public java.lang.String getValueInWei() {
      java.lang.Object ref = valueInWei_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        valueInWei_ = s;
        return s;
      }
    }
    /**
     * <code>string value_in_wei = 6;</code>
     */
    public com.google.protobuf.ByteString
        getValueInWeiBytes() {
      java.lang.Object ref = valueInWei_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        valueInWei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 7;
    private volatile java.lang.Object input_;
    /**
     * <code>string input = 7;</code>
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      }
    }
    /**
     * <code>string input = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (path_ != null) {
        output.writeMessage(1, getPath());
      }
      if (nonce_ != 0) {
        output.writeUInt32(2, nonce_);
      }
      if (gasLimit_ != 0) {
        output.writeUInt32(3, gasLimit_);
      }
      if (!getGasPriceInWeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gasPriceInWei_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, to_);
      }
      if (!getValueInWeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, valueInWei_);
      }
      if (!getInputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, input_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (path_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPath());
      }
      if (nonce_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, nonce_);
      }
      if (gasLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, gasLimit_);
      }
      if (!getGasPriceInWeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gasPriceInWei_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, to_);
      }
      if (!getValueInWeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, valueInWei_);
      }
      if (!getInputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, input_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jubiter.sdk.proto.EthereumProtos.TransactionETH)) {
        return super.equals(obj);
      }
      com.jubiter.sdk.proto.EthereumProtos.TransactionETH other = (com.jubiter.sdk.proto.EthereumProtos.TransactionETH) obj;

      if (hasPath() != other.hasPath()) return false;
      if (hasPath()) {
        if (!getPath()
            .equals(other.getPath())) return false;
      }
      if (getNonce()
          != other.getNonce()) return false;
      if (getGasLimit()
          != other.getGasLimit()) return false;
      if (!getGasPriceInWei()
          .equals(other.getGasPriceInWei())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getValueInWei()
          .equals(other.getValueInWei())) return false;
      if (!getInput()
          .equals(other.getInput())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPath()) {
        hash = (37 * hash) + PATH_FIELD_NUMBER;
        hash = (53 * hash) + getPath().hashCode();
      }
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce();
      hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGasLimit();
      hash = (37 * hash) + GAS_PRICE_IN_WEI_FIELD_NUMBER;
      hash = (53 * hash) + getGasPriceInWei().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + VALUE_IN_WEI_FIELD_NUMBER;
      hash = (53 * hash) + getValueInWei().hashCode();
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jubiter.sdk.proto.EthereumProtos.TransactionETH prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JUB.Proto.Ethereum.TransactionETH}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JUB.Proto.Ethereum.TransactionETH)
        com.jubiter.sdk.proto.EthereumProtos.TransactionETHOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_TransactionETH_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jubiter.sdk.proto.EthereumProtos.TransactionETH.class, com.jubiter.sdk.proto.EthereumProtos.TransactionETH.Builder.class);
      }

      // Construct using com.jubiter.sdk.proto.EthereumProtos.TransactionETH.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pathBuilder_ == null) {
          path_ = null;
        } else {
          path_ = null;
          pathBuilder_ = null;
        }
        nonce_ = 0;

        gasLimit_ = 0;

        gasPriceInWei_ = "";

        to_ = "";

        valueInWei_ = "";

        input_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jubiter.sdk.proto.EthereumProtos.internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor;
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.TransactionETH getDefaultInstanceForType() {
        return com.jubiter.sdk.proto.EthereumProtos.TransactionETH.getDefaultInstance();
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.TransactionETH build() {
        com.jubiter.sdk.proto.EthereumProtos.TransactionETH result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jubiter.sdk.proto.EthereumProtos.TransactionETH buildPartial() {
        com.jubiter.sdk.proto.EthereumProtos.TransactionETH result = new com.jubiter.sdk.proto.EthereumProtos.TransactionETH(this);
        if (pathBuilder_ == null) {
          result.path_ = path_;
        } else {
          result.path_ = pathBuilder_.build();
        }
        result.nonce_ = nonce_;
        result.gasLimit_ = gasLimit_;
        result.gasPriceInWei_ = gasPriceInWei_;
        result.to_ = to_;
        result.valueInWei_ = valueInWei_;
        result.input_ = input_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jubiter.sdk.proto.EthereumProtos.TransactionETH) {
          return mergeFrom((com.jubiter.sdk.proto.EthereumProtos.TransactionETH)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jubiter.sdk.proto.EthereumProtos.TransactionETH other) {
        if (other == com.jubiter.sdk.proto.EthereumProtos.TransactionETH.getDefaultInstance()) return this;
        if (other.hasPath()) {
          mergePath(other.getPath());
        }
        if (other.getNonce() != 0) {
          setNonce(other.getNonce());
        }
        if (other.getGasLimit() != 0) {
          setGasLimit(other.getGasLimit());
        }
        if (!other.getGasPriceInWei().isEmpty()) {
          gasPriceInWei_ = other.gasPriceInWei_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getValueInWei().isEmpty()) {
          valueInWei_ = other.valueInWei_;
          onChanged();
        }
        if (!other.getInput().isEmpty()) {
          input_ = other.input_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jubiter.sdk.proto.EthereumProtos.TransactionETH parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jubiter.sdk.proto.EthereumProtos.TransactionETH) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.jubiter.sdk.proto.CommonProtos.Bip44Path path_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jubiter.sdk.proto.CommonProtos.Bip44Path, com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder, com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder> pathBuilder_;
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public boolean hasPath() {
        return pathBuilder_ != null || path_ != null;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public com.jubiter.sdk.proto.CommonProtos.Bip44Path getPath() {
        if (pathBuilder_ == null) {
          return path_ == null ? com.jubiter.sdk.proto.CommonProtos.Bip44Path.getDefaultInstance() : path_;
        } else {
          return pathBuilder_.getMessage();
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder setPath(com.jubiter.sdk.proto.CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          path_ = value;
          onChanged();
        } else {
          pathBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder setPath(
          com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder builderForValue) {
        if (pathBuilder_ == null) {
          path_ = builderForValue.build();
          onChanged();
        } else {
          pathBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder mergePath(com.jubiter.sdk.proto.CommonProtos.Bip44Path value) {
        if (pathBuilder_ == null) {
          if (path_ != null) {
            path_ =
              com.jubiter.sdk.proto.CommonProtos.Bip44Path.newBuilder(path_).mergeFrom(value).buildPartial();
          } else {
            path_ = value;
          }
          onChanged();
        } else {
          pathBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public Builder clearPath() {
        if (pathBuilder_ == null) {
          path_ = null;
          onChanged();
        } else {
          path_ = null;
          pathBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder getPathBuilder() {
        
        onChanged();
        return getPathFieldBuilder().getBuilder();
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      public com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder getPathOrBuilder() {
        if (pathBuilder_ != null) {
          return pathBuilder_.getMessageOrBuilder();
        } else {
          return path_ == null ?
              com.jubiter.sdk.proto.CommonProtos.Bip44Path.getDefaultInstance() : path_;
        }
      }
      /**
       * <code>.JUB.Proto.Common.Bip44Path path = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jubiter.sdk.proto.CommonProtos.Bip44Path, com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder, com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder> 
          getPathFieldBuilder() {
        if (pathBuilder_ == null) {
          pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jubiter.sdk.proto.CommonProtos.Bip44Path, com.jubiter.sdk.proto.CommonProtos.Bip44Path.Builder, com.jubiter.sdk.proto.CommonProtos.Bip44PathOrBuilder>(
                  getPath(),
                  getParentForChildren(),
                  isClean());
          path_ = null;
        }
        return pathBuilder_;
      }

      private int nonce_ ;
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public int getNonce() {
        return nonce_;
      }
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public Builder setNonce(int value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 nonce = 2;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0;
        onChanged();
        return this;
      }

      private int gasLimit_ ;
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public int getGasLimit() {
        return gasLimit_;
      }
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public Builder setGasLimit(int value) {
        
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gas_limit = 3;</code>
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object gasPriceInWei_ = "";
      /**
       * <code>string gas_price_in_wei = 4;</code>
       */
      public java.lang.String getGasPriceInWei() {
        java.lang.Object ref = gasPriceInWei_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gasPriceInWei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gas_price_in_wei = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGasPriceInWeiBytes() {
        java.lang.Object ref = gasPriceInWei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gasPriceInWei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gas_price_in_wei = 4;</code>
       */
      public Builder setGasPriceInWei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPriceInWei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gas_price_in_wei = 4;</code>
       */
      public Builder clearGasPriceInWei() {
        
        gasPriceInWei_ = getDefaultInstance().getGasPriceInWei();
        onChanged();
        return this;
      }
      /**
       * <code>string gas_price_in_wei = 4;</code>
       */
      public Builder setGasPriceInWeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gasPriceInWei_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 5;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 5;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 5;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 5;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 5;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object valueInWei_ = "";
      /**
       * <code>string value_in_wei = 6;</code>
       */
      public java.lang.String getValueInWei() {
        java.lang.Object ref = valueInWei_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          valueInWei_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value_in_wei = 6;</code>
       */
      public com.google.protobuf.ByteString
          getValueInWeiBytes() {
        java.lang.Object ref = valueInWei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          valueInWei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value_in_wei = 6;</code>
       */
      public Builder setValueInWei(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueInWei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value_in_wei = 6;</code>
       */
      public Builder clearValueInWei() {
        
        valueInWei_ = getDefaultInstance().getValueInWei();
        onChanged();
        return this;
      }
      /**
       * <code>string value_in_wei = 6;</code>
       */
      public Builder setValueInWeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueInWei_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>string input = 7;</code>
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          input_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string input = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string input = 7;</code>
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string input = 7;</code>
       */
      public Builder clearInput() {
        
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>string input = 7;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        input_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JUB.Proto.Ethereum.TransactionETH)
    }

    // @@protoc_insertion_point(class_scope:JUB.Proto.Ethereum.TransactionETH)
    private static final com.jubiter.sdk.proto.EthereumProtos.TransactionETH DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jubiter.sdk.proto.EthereumProtos.TransactionETH();
    }

    public static com.jubiter.sdk.proto.EthereumProtos.TransactionETH getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionETH>
        PARSER = new com.google.protobuf.AbstractParser<TransactionETH>() {
      @java.lang.Override
      public TransactionETH parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionETH(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionETH> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionETH> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jubiter.sdk.proto.EthereumProtos.TransactionETH getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Ethereum_ContextCfgETH_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JUB_Proto_Ethereum_TransactionETH_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Jub_Ethereum.proto\022\022JUB.Proto.Ethereum" +
      "\032\020Jub_Common.proto\"4\n\rContextCfgETH\022\021\n\tm" +
      "ain_path\030\001 \001(\t\022\020\n\010chain_id\030\002 \001(\r\"\250\001\n\016Tra" +
      "nsactionETH\022)\n\004path\030\001 \001(\0132\033.JUB.Proto.Co" +
      "mmon.Bip44Path\022\r\n\005nonce\030\002 \001(\r\022\021\n\tgas_lim" +
      "it\030\003 \001(\r\022\030\n\020gas_price_in_wei\030\004 \001(\t\022\n\n\002to" +
      "\030\005 \001(\t\022\024\n\014value_in_wei\030\006 \001(\t\022\r\n\005input\030\007 " +
      "\001(\tB8\n\025com.jubiter.sdk.protoB\016EthereumPr" +
      "otos\242\002\016EthereumProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.jubiter.sdk.proto.CommonProtos.getDescriptor(),
        });
    internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JUB_Proto_Ethereum_ContextCfgETH_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Ethereum_ContextCfgETH_descriptor,
        new java.lang.String[] { "MainPath", "ChainId", });
    internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JUB_Proto_Ethereum_TransactionETH_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JUB_Proto_Ethereum_TransactionETH_descriptor,
        new java.lang.String[] { "Path", "Nonce", "GasLimit", "GasPriceInWei", "To", "ValueInWei", "Input", });
    com.jubiter.sdk.proto.CommonProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
